### ISSUE TITLE
Get all attendance of the student for given semester/month

### ISSUE THREAD

**Issue by ameypotnis** [ameypotnis/campus-service#2]
Develop an api to fetch student attendance for given moth

e.g. /api/students/1/attendance/BE/CS/201608/DistrubutedSystem
1 is roll number
201608 - yyyyMM form

**Comment by indrajeet183** [comment]
What should it return? I'm little confused

**Comment by ameypotnis** [comment]
{
  "roll": 123,
  "name" : "Amey Potnis",
  "standard" : "BE",
  "branch" : "CS",
  "attendance_dates": ["20160801", "20160802", "20160803", "20160804"],
  "attendance_present_days" : 20,
  "attendance_absent_days" : 5
}

**Comment by ameypotnis** [comment]
not needed
